export const projectsData = [
	{
		id: 1,
		src: "ESTUDIO_42_a_historia_reverbera_nas_letras_1920x1249.png",
		category: "Animation",
		title: "A história reverbera nas letras",
		client: "Estúdio 42",
		year: "2023",
		description:
			"Projeto desenvolvido para o Estúdio 42, no qual atuei na criação do storyboard, ilustrações e animação. O vídeo traduz, de forma visual e didática, a relação entre urbanização, literatura e pensamento social, traçando paralelos entre o caos das grandes cidades e o contexto europeu dos séculos XVII e XVIII. A narrativa aborda o Arcadismo, os ideais iluministas, a Revolução Francesa e a transição para o Romantismo, conectando razão, emoção e história em uma experiência clara e envolvente.",
		gallery: [
			"https://www.youtube.com/embed/EhZQMwFpZVc",
			"ESTUDIO_42_a_historia_reverbera_nas_letras_1500x1610_01.png",
			"ESTUDIO_42_a_historia_reverbera_nas_letras_1500x1610_02.png",
			"ESTUDIO_42_a_historia_reverbera_nas_letras_1500x1610_03.png",
			"ESTUDIO_42_a_historia_reverbera_nas_letras_1500x1610_04.png",
		],
	},
	{
		id: 2,
		src: "ESTUDIO_42_Como_os_animais_se_aquecem_1920x1249.png",
		category: "Animation",
		title: "Como os animais se aquecem",
		client: "Estúdio 42",
		year: "2024",
		description:
			"Projeto desenvolvido para o Estúdio 42, no qual atuei na criação do storyboard, ilustrações e animação, traduzindo conceitos científicos em uma linguagem visual clara e acessível. O vídeo explica por que os seres vivos não se distribuem igualmente pelo planeta, destacando a temperatura como um fator limitante da vida terrestre. A narrativa diferencia animais endotérmicos e ectotérmicos, relacionando metabolismo, reações químicas e adaptação ambiental, e mostra por que apenas aves e mamíferos conseguem manter o próprio calor corporal de forma eficiente.",
		gallery: [
			"https://www.youtube.com/embed/jdWFqj821Nc",
			"ESTUDIO_42_Como_os_animais_se_aquecem_1500x1610_01.png",
			"ESTUDIO_42_Como_os_animais_se_aquecem_1500x1610_02.png",
			"ESTUDIO_42_Como_os_animais_se_aquecem_1500x1610_03.png",
			"ESTUDIO_42_Como_os_animais_se_aquecem_1500x1610_04.png",
		],
	},
	{
		id: 3,
		src: "ESTUDIO_42_simetria_1920x1249.png",
		category: "Animation",
		title: "Reconhecendo a Simetria",
		client: "Estúdio 42",
		year: "2023",
		description:
			"Projeto desenvolvido para o Estúdio 42, no qual atuei na criação do storyboard, ilustrações e animação, transformando conceitos matemáticos em uma narrativa visual acessível e envolvente. O vídeo apresenta como a geometria e a simetria estão presentes na natureza, na arte e no cotidiano, explicando de forma didática a simetria axial, radial e de translação por meio de exemplos visuais, como paisagens, obras artísticas e o piso paulista de São Paulo, estimulando a observação e a criatividade do espectador",
		gallery: [
			"https://www.youtube.com/embed/3eJRGF0s5WQ?si=9-obQZtNy-mMclXg",
			"ESTUDIO_42_simetria_1500x1610_01.png",
			"ESTUDIO_42_simetria_1500x1610_02.png",
			"ESTUDIO_42_simetria_1500x1610_03.png",
			"ESTUDIO_42_simetria_1500x1610_04.png",
		],
	},
	{
		id: 4,
		src: "JOVEM_NERD_BARALHO_1920x1249.png",
		category: "Games",
		title: "Baralho de Luxo - Jovem Nerd",
		client: "Jovem Nerd",
		year: "2022",
		description:
			"Proposta de projeto desenvolvida para o Jovem Nerd, na qual atuei na concepção criativa e ilustração de um baralho de luxo. A ideia transforma os principais participantes do programa em personagens ilustrados em realismo, reinterpretados como figuras aristocráticas dos períodos clássico e vitoriano, criando um contraste elegante entre cultura pop e estética histórica. O projeto foi pensado com foco em acabamento premium, prevendo cartas em PVC 300g e box em couchê 300g, reforçando o caráter colecionável e exclusivo da peça.",
		gallery: [
			"JOVEM_NERD_BARALHO_1500x1610_01.png",
			"JOVEM_NERD_BARALHO_1500x1610_02.png",
			"JOVEM_NERD_BARALHO_1500x1610_03.png",
			"JOVEM_NERD_BARALHO_1500x1610_04.png",
		],
	},
	{
		id: 5,
		src: "PORRADA_DEUSAS_E_MONSTROS_1920x1249.png",
		category: "Games",
		title: "Porrada! Deusas & Monstros",
		client: "Projeto Pessoal",
		year: "2025",
		description:
			"Projeto autoral desenvolvido por mim, no qual atuei desde a criação das mecânicas, design dos cards e toda a ilustração. Porrada, Deusas e Monstros é um RPG cooperativo em formato cardgame deck builder, criado para até 6 jogadores que querem entrar direto na ação, sem fichas complexas ou livros extensos. O jogo apresenta heróis lendários, campanhas épicas, masmorras imprevisíveis e desafios cooperativos ambientados na Torre Infinita, onde monstros e Deusas podem mudar o rumo da aventura a qualquer momento. A experiência é ampliada com o PDM Dice App, que reúne fichas digitais, rolagem de dados e manual, reforçando o caráter acessível, dinâmico e altamente rejogável do projeto.",
		gallery: [
			"https://www.youtube.com/embed/Gtz8qzm0JFo?si=dyFGX_ZgyWzzTk87",
			"PORRADA_DEUSAS_E_MONSTROS_1500x1610_01.png",
			"PORRADA_DEUSAS_E_MONSTROS_1500x1610_02.png",
			"PORRADA_DEUSAS_E_MONSTROS_1500x1610_03.png",
			"PORRADA_DEUSAS_E_MONSTROS_1500x1610_04.png",
		],
	},
	{
		id: 6,
		src: "gamescola_mechafish_1920x1249.png",
		category: "Games",
		title: "Mechafish",
		client: "Gamescola",
		year: "2024",
		description:
			"Projeto Mecha Fish, desenvolvido para fins educacionais na GAMESCOLA, no qual fui responsável pelo design e ilustração do personagem. Inspirado no personagem criado no filme Megamente, o projeto foi concebido como um modelo completo para treinamento em processos de animação para games. O personagem foi desenvolvido utilizando a técnica de cut-out e configurado no DragonBones, estando preparado para implementação em uma plataforma game 2.5D no Unity, com estrutura pensada para integração via JSON, reforçando seu uso prático em pipelines de produção de jogos.",
		gallery: [
			"https://www.youtube.com/embed/jvIX0EbHwIY",
			"gamescola_mechafish_1500x1610_01.png",
			"gamescola_mechafish_1500x1610_02.png",
			"gamescola_mechafish_1500x1610_03.png",
			"gamescola_mechafish_1500x1610_04.png",
		],
	},
	{
		id: 7,
		src: "gamescola_ozob_1920x1249.png",
		category: "Games",
		title: "OZOB",
		client: "Gamescola",
		year: "2024",
		description:
			"Projeto desenvolvido para fins educacionais na UNINTER, no qual atuei no design e ilustração do personagem, aplicado a um treinamento em processos de animação para games. O famoso personagem do Nerdcast Cyberpunk e do jogo Cyberpunk 2077 serviu como referência conceitual para o estudo. A personagem foi construída com a técnica de cut-out e configurada no DragonBones, estando preparada para implementação em uma plataforma game 2.5D no Unity, com estrutura compatível com programação em JSON, seguindo um pipeline profissional de produção.",
		gallery: [
			"https://www.youtube.com/embed/3fkdVgCAN9U",
			"gamescola_ozob_1500x1610_01.png",
			"gamescola_ozob_1500x1610_02.png",
			"gamescola_ozob_1500x1610_03.png",
			"gamescola_ozob_1500x1610_04.png",
		],
	},
	{
		id: 9,
		src: "PERTO_BILINGUE_REINASSANCE_1920x1249.png",
		category: "Illustrations",
		title: "Renaissance",
		client: "Perto Bilíngue",
		year: "2021",
		description:
			"Projetos desenvolvidos para a Perto Bilíngue, sob o selo PERTO LAB, nos quais atuei como Diretor de Arte em diversas frentes criativas. Neste projeto específico, também fui responsável pela ilustração e pelo design, contribuindo de forma integral para a construção visual do material. Renaissance é um material didático ilustrado e interativo, voltado ao público do ensino médio, criado para dar suporte a uma metodologia própria de ensino de idiomas, unindo linguagem visual, engajamento e clareza pedagógica.",
		gallery: [
			"PERTO_BILINGUE_REINASSANCE_1500x1610_01.png",
			"PERTO_BILINGUE_REINASSANCE_1500x1610_02.png",
			"PERTO_BILINGUE_REINASSANCE_1500x1610_03.png",
			"PERTO_BILINGUE_REINASSANCE_1500x1610_04.png",
		],
	},
	{
		id: 10,
		src: "PERTO_BILINGUE_HONEY_BEES_1920x1249.png",
		category: "Illustrations",
		title: "Honey Bees",
		client: "Perto Bilíngue",
		year: "2021",
		description:
			"Projeto desenvolvido para a Perto Bilíngue, sob o selo PERTO LAB, no qual atuei como Diretor de Arte, além de colaborar na construção visual do material. Honey Bees é um material didático ilustrado e interativo, voltado ao público do ensino médio, criado para apoiar uma metodologia própria de ensino de idiomas, combinando narrativa visual, engajamento e clareza pedagógica.",
		gallery: [
			"PERTO_BILINGUE_HONEY_BEES_1500x1610_01.png",
			"PERTO_BILINGUE_HONEY_BEES_1500x1610_02.png",
			"PERTO_BILINGUE_HONEY_BEES_1500x1610_03.png",
			"PERTO_BILINGUE_HONEY_BEES_1500x1610_04.png",
		],
	},
	{
		id: 11,
		src: "PERTO_BILINGUE_INDIOS_1920x1249.png",
		category: "Illustrations",
		title: "The Amazon Forest",
		client: "Perto Bilíngue",
		year: "2021",
		description:
			"Projeto desenvolvido para a Perto Bilíngue, sob o selo PERTO LAB, no qual atuei como Diretor de Arte, contribuindo para a construção visual e conceitual do material. The Amazon Forest é um material didático ilustrado e interativo, voltado ao público do ensino médio, criado para apoiar uma metodologia própria de ensino de idiomas, unindo conteúdo educacional, narrativa visual e engajamento pedagógico.",
		gallery: [
			"PERTO_BILINGUE_INDIOS_1500x1610_01.png",
			"PERTO_BILINGUE_INDIOS_1500x1610_02.png",
			"PERTO_BILINGUE_INDIOS_1500x1610_03.png",
			"PERTO_BILINGUE_INDIOS_1500x1610_04.png",
		],
	},
	{
		id: 12,
		src: "ULTRACOFFEE_DIA_MUNIDAL_DO_CAFÉ_1920x1249.png",
		category: "Illustrations",
		title: "ULTRA COFFEE - Dia do Café",
		client: "UltraCoffee Brasil",
		year: "2021",
		description:
			"Projeto de ilustração desenvolvido para a Ultracoffee Brasil para comemorar o dia do café, no qual utilizei a técnica de Illustration System para a construção modular das cenas. A proposta visual foi criar uma estética inspirada em games mobile, com elementos interativos e narrativa visual dinâmica. A ilustração conta com diversos easter eggs espalhados pela composição, convidando o público a explorar cada detalhe e descobrir todas as referências escondidas.",
		gallery: [
			"ULTRACOFFEE_DIA_MUNIDAL_DO_CAFÉ_1500x1610_01.png",
			"ULTRACOFFEE_DIA_MUNIDAL_DO_CAFÉ_1500x1610_02.png",
			"ULTRACOFFEE_DIA_MUNIDAL_DO_CAFÉ_1500x1610_03.png",
			"ULTRACOFFEE_DIA_MUNIDAL_DO_CAFÉ_1500x1610_04.png",
		],
	},
	{
		id: 13,
		src: "ULTRACOFFE_MASCOTE_1920x1249.png",
		category: "Illustrations",
		title: "ULTRA COFFEE - Mocha",
		client: "UltraCoffee Brasil",
		year: "2021",
		description:
			"Mocha é o mascote desenvolvido para o Ultra Coffee. A partir de estudos e análises de perfil de público e hábitos de consumo, foram definidos traços e uma estrutura semelhante a desenhos como Pokémon a fim de aumentar a conexão com o personagem e, logo, com a marca. Em breve, Mocha ajudará a sustentar as mídias digitais da marca, podendo ser utilizado em diversas aplicações e outros projetos, como games mobile, pelúcias e action figures. Mocha é arrojado, destemido e fofinho. Quem não gostaria de ter um Mocha como seu pet?!",
		gallery: [
			"ULTRACOFFE_MASCOTE_1500x1610_01.png",
			"ULTRACOFFE_MASCOTE_1500x1610_02.png",
			"ULTRACOFFE_MASCOTE_1500x1610_03.png",
			"ULTRACOFFE_MASCOTE_1500x1610_04.png",
		],
	},
	{
		id: 14,
		src: "GOLDEN_KUAN_YIN_1920x1249.png",
		category: "Illustrations",
		title: "Golden Kuan Yin",
		client: "Particular",
		year: "2019",
		description:
			"Ilustração sob encomenda da Golden Kuan Yin, na qual desenvolvi uma representação em tons dourados de Guanyin, a Bodhisattva da Compaixão, Misericórdia e Bondade, amplamente reverenciada nas tradições budistas e taoistas do Leste Asiático. O projeto busca traduzir visualmente o caráter sereno e espiritual da divindade, unindo simbolismo, elegância e respeito cultural em uma composição contemplativa e detalhada.",
		gallery: [
			"GOLDEN_KUAN_YIN_1500x1610_01.png",
			"GOLDEN_KUAN_YIN_1500x1610_02.png",
			"GOLDEN_KUAN_YIN_1500x1610_03.png",
			"GOLDEN_KUAN_YIN_1500x1610_04.png",
		],
	},
	{
		id: 15,
		src: "JOVEMNERD_CAMISA_E_ASSIM_QUE_MEU_FUSCA_ANDA_1920x1249.png",
		category: "Illustrations",
		title: "É assim que meu fusca anda",
		client: "Jovem Nerd",
		year: "2022",
		description:
			"Ilustração desenvolvida para o Jovem Nerd, que posteriormente se transformou em estampa de camiseta da Nerdstore. A arte é inspirada na cena inicial do filme Gladiador, reinterpretada de forma bem-humorada: um bárbaro grita, em um idioma incompreensível, algo que soa como “É assim que meu Fusca anda!”, enquanto ao fundo os guerreiros respondem com a onomatopeia “VRUUUM”. O projeto mistura referência cinematográfica, cultura pop e humor, criando uma ilustração icônica e memorável para o público da marca.",
		gallery: [
			"JOVEMNERD_CAMISA_E_ASSIM_QUE_MEU_FUSCA_ANDA_1500x1610_01.png",
			"JOVEMNERD_CAMISA_E_ASSIM_QUE_MEU_FUSCA_ANDA_1500x1610_02.png",
			"JOVEMNERD_CAMISA_E_ASSIM_QUE_MEU_FUSCA_ANDA_1500x1610_03.png",
			"JOVEMNERD_CAMISA_E_ASSIM_QUE_MEU_FUSCA_ANDA_1500x1610_04.png",
		],
	},
	{
		id: 16,
		src: "JUJUTSU_KAISEN_1920x1249.png",
		category: "Illustrations",
		title: "JUJUTSU Kaisen",
		client: "Particular",
		year: "2026",
		description:
			"Projeto de ilustração sob encomenda, no qual atuei com total liberdade criativa para reinterpretar uma cena de Jujutsu Kaisen na luta do Sukuna contra o Mahoraga no arco Insidente de Shibuya. Tudo no meu estilo, combinando ação, exagero e humor. A proposta foi inspirada no humor afiado do @‌zerenacho, resultando em uma composição intensa, caótica na medida certa e cheia de personalidade. Todo o cenário foi criado do zero, pensado para potencializar a energia da cena e reforçar a narrativa visual, mostrando como boas referências e espaço criativo elevam o impacto final do projeto.",
		gallery: [
			"JUJUTSU_KAISEN_1500x1610_01.png",
			"JUJUTSU_KAISEN_1500x1610_02.png",
			"JUJUTSU_KAISEN_1500x1610_03.png",
			"JUJUTSU_KAISEN_1500x1610_04.png",
			"JUJUTSU_KAISEN_1920x300_barra.png"
		],
	},
	{
		id: 17,
		src: "SENAI_MEGAMAN_1920x1249.png",
		category: "Illustrations",
		title: "Megaman Zero",
		client: "SENAI Artes Gráficas",
		year: "2016",
		description:
			"Projeto pessoal e educacional desenvolvido em 2016, durante meu período como professor no Senai Artes Gráficas, no Rio de Janeiro. A proposta nasceu da necessidade de mostrar aos alunos que a criatividade vai além da ferramenta, especialmente em um contexto onde nem todos tinham acesso ao computador ou segurança para ilustrar no digital. O personagem “Zero” foi criado inicialmente de forma totalmente analógica, em sketchbook, utilizando papel e caneta, e posteriormente finalizado com pintura digital no Photoshop. O processo gerou reflexões valiosas sobre fluxo criativo, adaptação de técnicas e inclusão no ensino, além de inspirar alunos que hoje atuam profissionalmente na área. Um agradecimento especial ao @‌marceloghizi, @‌barretopdr e ao então aluno @‌phil.tattoo, que ajudaram a transformar essa experiência em um marco criativo e humano.",
		gallery: [
			"SENAI_MEGAMAN_1500x1610_01.png",
			"SENAI_MEGAMAN_1500x1610_02.png",
			"SENAI_MEGAMAN_1500x1610_03.png",
			"SENAI_MEGAMAN_1500x1610_04.png",
		],
	},
	{
		id: 18,
		src: "MARATONA_COM_CAFE_NERD_1920x1249.png",
		category: "Illustrations",
		title: "Maratona com café 01",
		client: "Maratona com Café",
		year: "2025",
		description:
			"Ilustração desenvolvida para o @‌maratonacomcafe_, em um projeto autoral repleto de referências e identidade pessoal. A proposta foi criar um avatar heroico em idle pose, inspirado em telas de seleção de personagens, representando o Marcelo sempre pronto para a próxima aventura. O visual mistura paixões pela cultura oriental, com referências a tokusatsu, animes e mangás, costuradas de forma coesa e cheia de personalidade. Entre os detalhes estão a jaqueta inspirada no Wolverine, o elmo do Cavaleiro de Capricórnio, a Pandora Box, o Digivice do Gabumon e, claro, a xícara de café, símbolo do canal e combustível de cada maratona. Um projeto que celebra narrativa visual, fandom e criatividade — e que marca o início de um pack ainda mais épico.",
		gallery: [
			"MARATONA_COM_CAFE_NERD_1500x1610_01.png",
			"MARATONA_COM_CAFE_NERD_1500x1610_02.png",
			"MARATONA_COM_CAFE_NERD_1500x1610_03.png",
			"MARATONA_COM_CAFE_NERD_1500x1610_04.png",
		],
	},
	{
		id: 19,
		src: "MARATONA_COM_CAFE_GAME_1920x1249.png",
		category: "Illustrations",
		title: "Maratona com café 02",
		client: "Maratona com Café",
		year: "2025",
		description:
			"Ilustração desenvolvida para o @‌maratonacomcafe_, como parte de um conjunto de artes que expandem o universo visual do canal. Neste fragmento do projeto, o avatar do Marcelo aparece em cena durante o gameplay, com a proposta de dar vida própria ao controle, transformando o ato de jogar em narrativa visual. A composição explora ação, movimento e humor, além de esconder diversos easter eggs espalhados pela arte, convidando o público a observar cada detalhe e descobrir todas as referências.",
		gallery: [
			"MARATONA_COM_CAFE_GAME_1500x1610_01.png",
			"MARATONA_COM_CAFE_GAME_1500x1610_02.png",
			"MARATONA_COM_CAFE_GAME_1500x1610_03.png",
			"MARATONA_COM_CAFE_GAME_1500x1610_04.png",
		],
	},
	{
		id: 20,
		src: "MARATONA_COM_CAFE_CINEMA_1920x1249.png",
		category: "Illustrations",
		title: "Maratona com café 03",
		client: "Maratona com Café",
		year: "2025",
		description:
			"Ilustração desenvolvida para o @‌maratonacomcafe_, como parte da expansão visual do universo do canal. Neste fragmento do projeto, o avatar do Marcelo se lança para dentro do universo do cinema, simbolizando a imersão total nas histórias, gêneros e referências que movem o conteúdo do canal. A cena explora dinamismo, narrativa e exagero visual, reunindo múltiplas referências cinematográficas e diversos easter eggs espalhados pela composição, convidando o público a explorar cada detalhe da ilustração.",
		gallery: [
			"MARATONA_COM_CAFE_CINEMA_1500x1610_01.png",
			"MARATONA_COM_CAFE_CINEMA_1500x1610_02.png",
			"MARATONA_COM_CAFE_CINEMA_1500x1610_03.png",
			"MARATONA_COM_CAFE_CINEMA_1500x1610_04.png",
		],
	},
	{
		id: 21,
		src: "KYUDO_1920x1249.png",
		category: "Illustrations",
		title: "Selo oficial do 11º Seminário Brasileiro de Kyudo",
		client: "Seminário Brasileiro de Kyudo de Itajaí",
		year: "2025",
		description:
			"Ilustração criada como selo oficial do 11º Seminário Brasileiro de Kyudo, que acontecerá em Itajaí. A arte reúne elementos simbólicos da cidade, como a flor de buganvília e o mar, integrados à figura de uma arqueira de Kyudo, representando a tradição, a disciplina e a conexão entre corpo, mente e ambiente. O resultado é um selo que une identidade local, cultura japonesa e significado esportivo em uma composição elegante e representativa.",
		gallery: [
			"KYUDO_1500x1610_01.png",
			"KYUDO_1500x1610_02.png",
			"KYUDO_1500x1610_03.png",
			"KYUDO_1500x1610_04.png",
		],
	},
	{
		id: 22,
		src: "GAMESCOLA_MASCOTE_CAPSLOCK_1920x1249.png",
		category: "Illustrations",
		title: "Capslock Mascote GAMESCOLA",
		client: "GAMESCOLA",
		year: "2025",
		description:
			"Projeto de redesign de mascote desenvolvido para a @‌gamescola, com foco em atualizar e fortalecer a identidade da marca. Fui responsável por repaginar o Capslock, personagem já icônico da empresa, criando uma nova linguagem visual mais conectada ao público atual. O processo envolveu estudos de forma, poses e expressões, resultando em um mascote mais dinâmico, versátil e cheio de personalidade. Um trabalho que reforça como a evolução de um personagem acompanha o crescimento da marca e mantém vivo o elo entre identidade, emoção e reconhecimento.",
		gallery: [
			"GAMESCOLA_MASCOTE_CAPSLOCK_1500x1610_01.png",
			"GAMESCOLA_MASCOTE_CAPSLOCK_1500x1610_02.png",
			"GAMESCOLA_MASCOTE_CAPSLOCK_1500x1610_03.png",
			"GAMESCOLA_MASCOTE_CAPSLOCK_1500x1610_04.png",
		],
	},
	{
		id: 23,
		src: "GAMESCOLA_MASCOTE_SHIFT_1920x1249.png",
		category: "Illustrations",
		title: "Shift Mascote GAMESCOLA",
		client: "GAMESCOLA",
		year: "2025",
		description:
			"Projeto de criação de mascote desenvolvido para a @‌gamescola, pensado especialmente para conversar com o público feminino e fazer companhia ao já conhecido Capslock. Fui responsável pela concepção visual e design da Shift, uma personagem cheia de personalidade, criada para ampliar a representatividade e fortalecer o universo da marca. O processo envolveu estudos, sketches e desenvolvimento de poses finais, resultando em uma mascote carismática, versátil e alinhada à essência da Gamescola.",
		gallery: [
			"GAMESCOLA_MASCOTE_SHIFT_1500x1610_01.png",
			"GAMESCOLA_MASCOTE_SHIFT_1500x1610_02.png",
			"GAMESCOLA_MASCOTE_SHIFT_1500x1610_03.png",
			"GAMESCOLA_MASCOTE_SHIFT_1500x1610_04.png",
		],
	},
	{
		id: 24,
		src: "ENERZON_1920x1249.png",
		category: "Illustrations",
		title: "Enerzon Ilustração Institucional",
		client: "Enerzon",
		year: "2025",
		description:
			"Pacote de ilustrações desenvolvido para a ENERZON, criado para a apresentação visual do produto em diferentes pontos de contato da marca, como site, catálogos e materiais promocionais. Todo o projeto foi desenvolvido a partir da técnica modular de Illustration System, permitindo agilidade na criação, fácil adaptação das cenas e consistência visual entre os diversos materiais, reforçando a identidade da marca de forma versátil e eficiente.",
		gallery: [
			"ENERZON_1500x1610_01.png",
			"ENERZON_1500x1610_02.png",
			"ENERZON_1500x1610_03.png",
			"ENERZON_1500x1610_04.png",
		],
	},
	{
		id: 25,
		src: "DBZ_TRUNKS_1920x1249.png",
		category: "Illustrations",
		title: "FRIIIIIIZER! DBZ Trunks",
		client: "Gamescola e UNINTER",
		year: "2025",
		description:
			"Ilustração criada em para minhas aulas de ilustração e comunicação visual, inspirada em Dragon Ball Z, como exercício prático para discutir processos criativos. A proposta foi mostrar que criar não é um ato que surge é partir do nada, mas fundir universos e referências: neste exemplo, a estética e energia de Dragon Ball Z se misturam ao visual e ao humor de Hora de Aventura. A ilustração nasce como ferramenta didática para reforçar que toda criação exige repertório, observação e boas referências — um conceito simples, mas fundamental para o desenvolvimento criativo.",
		gallery: [
			"DBZ_TRUNKS_1500x1610_01.png",
			"DBZ_TRUNKS_1500x1610_02.png",
			"DBZ_TRUNKS_1500x1610_03.png",
			"DBZ_TRUNKS_1500x1610_04.png",
		],
	},
	{
		id: 26,
		src: "DBZ_BROLLY_VS_GOKUEVEGETA_1920x1249.png",
		category: "Illustrations",
		title: "Brolly surrando Goku e Vegeta",
		client: "Gamescola e UNINTER",
		year: "2025",
		description:
			"Ilustração criada em para minhas aulas de ilustração e comunicação visual, inspirada em Dragon Ball Z, como exercício prático para discutir processos criativos. A proposta foi mostrar que criar não é um ato que surge é partir do nada, mas fundir universos e referências: neste exemplo, a estética e energia de Dragon Ball Z se misturam ao visual e ao humor de Hora de Aventura. A ilustração nasce como ferramenta didática para reforçar que toda criação exige repertório, observação e boas referências — um conceito simples, mas fundamental para o desenvolvimento criativo.",
		gallery: [
			"DBZ_BROLLY_VS_GOKUEVEGETA_1500x1610_01.png",
			"DBZ_BROLLY_VS_GOKUEVEGETA_1500x1610_02.png",
			"DBZ_BROLLY_VS_GOKUEVEGETA_1500x1610_03.png",
			"DBZ_BROLLY_VS_GOKUEVEGETA_1500x1610_04.png",
		],
	},
	{
		id: 27,
		src: "dbz_brolly_VS_GOgeta_1920x1249.png",
		category: "Illustrations",
		title: "Brolly VS Gogeta",
		client: "Gamescola e UNINTER",
		year: "2025",
		description:
			"Ilustração criada em para minhas aulas de ilustração e comunicação visual, inspirada em Dragon Ball Z, como exercício prático para discutir processos criativos. A proposta foi mostrar que criar não é um ato que surge é partir do nada, mas fundir universos e referências: neste exemplo, a estética e energia de Dragon Ball Z se misturam ao visual e ao humor de Hora de Aventura. A ilustração nasce como ferramenta didática para reforçar que toda criação exige repertório, observação e boas referências — um conceito simples, mas fundamental para o desenvolvimento criativo.",
		gallery: [
			"dbz_brolly_VS_GOgeta_1500x1610_01.png",
			"dbz_brolly_VS_GOgeta_1500x1610_02.png",
			"dbz_brolly_VS_GOgeta_1500x1610_03.png",
			"dbz_brolly_VS_GOgeta_1500x1610_04.png",
		],
	},
	{
		id: 28,
		src: "ANDRESSA_AMAZON_1920x1249.png",
		category: "Illustrations",
		title: "Amazona",
		client: "Andressa Silva",
		year: "2025",
		description:
			"Ilustração sob encomenda, criada para a @‌andressa77rp, com a proposta de representá-la como uma guerreira amazona — forte, imponente e destemida. Inspirada diretamente nos filmes da Mulher-Maravilha, a arte traduz sua rotina de alta performance no crossfit em uma narrativa visual poderosa. Armadura, postura e expressão foram cuidadosamente pensados para refletir sua essência: uma mulher que encara desafios de frente e carrega força tanto no corpo quanto na presença.",
		gallery: [
			"ANDRESSA_AMAZON_1500x1610_01.png",
			"ANDRESSA_AMAZON_1500x1610_02.png",
			"ANDRESSA_AMAZON_1500x1610_03.png",
			"ANDRESSA_AMAZON_1500x1610_04.png",
		],
	},
	{
		id: 29,
		src: "ARTES_PESSOAIS_1920x1249.png",
		category: "Illustrations",
		title: "Artes Pessoais e Autorais",
		client: "Pessoal",
		year: "2026",
		description:
			"Conjunto de artes pessoais e autorais, reunindo ideias, estudos e conceitos de projetos que ainda sairão do papel  ou que existem simplesmente pelo prazer de criar. São ilustrações feitas para experimentar estilos, narrativas e soluções visuais, funcionando como um espaço livre de exploração criativa, diversão e desenvolvimento artístico.",
		gallery: [
			"ARTES_PESSOAIS_1500x1610_01.png",
			"ARTES_PESSOAIS_1500x1610_02.png",
			"ARTES_PESSOAIS_1500x1610_03.png",
			"ARTES_PESSOAIS_1500x1610_04.png",
		],
	},
];
